name: unshelf_seller
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  http: ^1.2.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^4.0.4
  provider: ^6.1.2
  google_sign_in: ^5.2.1
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  nanoid: ^1.0.0
  fl_chart: ^0.69.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_osm_plugin: ^1.3.4
  flutter_map_cancellable_tile_provider: ^3.0.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 23
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
